packages:
  - "apps/*"
  - "packages/*"
  - "configs/*"

catalogs:
  core:
    react: "^19.1.1"
    react-dom: "^19.1.1"
    typescript: "^5"
    tailwindcss: "^4.1.12"
    "@tailwindcss/postcss": "^4.1.10"
    postcss: "^8.5.6"
    zod: "^4.0.2"
    tsdown: "^0.14.2"
    rolldown: "^1.0.0-beta.34"
  types:
    "@types/node": "^20"
    "@types/react": "^19"
    "@types/react-dom": "^19"