import { fontVariables } from '@/lib/fonts';
import '@workspace/ui/globals.css';
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import './globals.css';

export const metadata: Metadata = {
  title: 'Promptverse AI',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${fontVariables} antialiased`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
