name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem it Solves
      description: What problem does this solve?
      placeholder: Currently I have to...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternatives you've tried?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Extension UI
        - Prompt Enhancement
        - Platform Support
        - Documentation
        - Other
    validations:
      required: true
