# Ruler Configuration File
# See https://okigu.com/ruler for documentation.


default_agents = ["windsurf"]

[agents.copilot]
enabled = true
output_path = ".github/copilot-instructions.md"

[agents.claude]
enabled = true
output_path = "CLAUDE.md"
