import { NavigationBar } from "@/components/shared/navigation-bar";
import { fontVariables } from "@/lib/fonts";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Promptverse AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${fontVariables} antialiased`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
